import type {
  SourceRecord, Outreach, ComplianceLogEntry, Opportunity, Newsletter,
} from "@/lib/types";

// ============================================================
// Extended Mock Data — Sprint 4: Sources, Outreach, Compliance
// ============================================================

export const MOCK_SOURCE_RECORDS: SourceRecord[] = [
  {
    id: "src-1",
    source_type: "news",
    title: "Compass Datacenters Plans 120MW Campus in Mesa, AZ",
    url: "https://datacenterdynamics.com/compass-mesa-campus",
    raw_content: "Compass Datacenters has secured 85 acres in Mesa, AZ for a new 120MW data center campus. Phase 1 targets 60MW with a $350M total investment. Construction expected to begin Q4 2026.",
    extracted_data: { mw: 120, phase1_mw: 60, acres: 85, estimated_cost: 350000000 },
    sector_guess: "data_center",
    location_guess: "Mesa, AZ",
    amount_guess: 350000000,
    relevance_score: 92,
    status: "new",
    converted_project_id: null,
    dismissed_reason: null,
    created_at: "2026-03-08T06:00:00Z",
  },
  {
    id: "src-2",
    source_type: "news",
    title: "Hines JV Announces $280M Luxury Resi Tower in Austin",
    url: "https://bisnow.com/hines-austin-tower",
    raw_content: "Hines, in a joint venture with a Middle Eastern sovereign fund, is planning a 42-story luxury residential tower in downtown Austin. Total development cost estimated at $280M.",
    extracted_data: { stories: 42, units_est: 350, jv_partner: "sovereign fund" },
    sector_guess: "cre",
    location_guess: "Austin, TX",
    amount_guess: 280000000,
    relevance_score: 85,
    status: "new",
    converted_project_id: null,
    dismissed_reason: null,
    created_at: "2026-03-07T14:30:00Z",
  },
  {
    id: "src-3",
    source_type: "linkedin",
    title: "CEO post: Breaking ground on 200-key Hilton Garden Inn, Savannah",
    url: null,
    raw_content: "Excited to announce we're breaking ground on a 200-key Hilton Garden Inn in Savannah's historic district. Seeking equity partners for the $65M project.",
    extracted_data: { keys: 200, flag: "Hilton Garden Inn" },
    sector_guess: "hospitality",
    location_guess: "Savannah, GA",
    amount_guess: 65000000,
    relevance_score: 78,
    status: "reviewed",
    converted_project_id: null,
    dismissed_reason: null,
    created_at: "2026-03-06T10:00:00Z",
  },
  {
    id: "src-4",
    source_type: "public_filing",
    title: "FERC Filing: SunBridge Solar 300MW Project, West Texas",
    url: "https://elibrary.ferc.gov/sunbridge-300mw",
    raw_content: "SunBridge Energy LLC has filed for interconnection of a 300MW solar + 150MW battery storage facility in Pecos County, TX. Estimated total investment: $420M.",
    extracted_data: { mw_solar: 300, mw_battery: 150, filing_type: "interconnection" },
    sector_guess: "energy",
    location_guess: "Pecos County, TX",
    amount_guess: 420000000,
    relevance_score: 74,
    status: "new",
    converted_project_id: null,
    dismissed_reason: null,
    created_at: "2026-03-05T08:00:00Z",
  },
  {
    id: "src-5",
    source_type: "referral",
    title: "Referral: Industrial campus developer seeking $40M mezz",
    url: null,
    raw_content: "Contact from NAIOP conference — industrial developer in Charlotte looking for $40M mezzanine debt for a 600K SF spec warehouse project.",
    extracted_data: { sqft: 600000, capital_need: "mezzanine debt" },
    sector_guess: "cre",
    location_guess: "Charlotte, NC",
    amount_guess: 40000000,
    relevance_score: 81,
    status: "new",
    converted_project_id: null,
    dismissed_reason: null,
    created_at: "2026-03-04T16:00:00Z",
  },
  {
    id: "src-6",
    source_type: "news",
    title: "Small Office Renovation in Tulsa — $2M budget",
    url: "https://tulsaworld.com/small-office-reno",
    raw_content: "Local developer plans a $2M office renovation in downtown Tulsa.",
    extracted_data: {},
    sector_guess: "cre",
    location_guess: "Tulsa, OK",
    amount_guess: 2000000,
    relevance_score: 18,
    status: "dismissed",
    converted_project_id: null,
    dismissed_reason: "Below $5M threshold",
    created_at: "2026-03-03T09:00:00Z",
  },
];

export const MOCK_OUTREACH: Outreach[] = [
  {
    id: "out-1",
    contact_id: "con-1",
    project_id: "proj-1",
    channel: "email",
    direction: "outbound",
    subject: "Vertex Ashburn Phase 2 — Capital Partner Opportunity",
    body: "Hi Michael, following up from our conversation at NAIOP. We have strong interest from capital partners for the Phase 2 campus...",
    template_id: null,
    status: "replied",
    scheduled_at: null,
    sent_at: "2026-03-05T16:00:00Z",
    sequence_position: 1,
    sequence_id: null,
    compliance_approved: true,
    compliance_approved_by: "system",
    compliance_approved_at: "2026-03-05T15:55:00Z",
    created_by: null,
    created_at: "2026-03-05T15:50:00Z",
  },
  {
    id: "out-2",
    contact_id: "con-3",
    project_id: "proj-2",
    channel: "email",
    direction: "outbound",
    subject: "The Vue at Knox — Preferred Equity Discussion",
    body: "James, great connecting with you. I'd love to discuss the preferred equity opportunity for The Vue at Knox...",
    template_id: null,
    status: "opened",
    scheduled_at: null,
    sent_at: "2026-03-06T10:00:00Z",
    sequence_position: 1,
    sequence_id: null,
    compliance_approved: true,
    compliance_approved_by: "system",
    compliance_approved_at: "2026-03-06T09:55:00Z",
    created_by: null,
    created_at: "2026-03-06T09:50:00Z",
  },
  {
    id: "out-3",
    contact_id: "con-3",
    project_id: "proj-2",
    channel: "phone",
    direction: "outbound",
    subject: "Follow-up call — The Vue at Knox equity",
    body: "Called James to discuss terms. He's interested in a 12% pref return structure. Sending term sheet this week.",
    template_id: null,
    status: "sent",
    scheduled_at: null,
    sent_at: "2026-03-07T14:00:00Z",
    sequence_position: 2,
    sequence_id: null,
    compliance_approved: true,
    compliance_approved_by: "system",
    compliance_approved_at: "2026-03-07T13:55:00Z",
    created_by: null,
    created_at: "2026-03-07T13:50:00Z",
  },
  {
    id: "out-4",
    contact_id: "con-2",
    project_id: "proj-3",
    channel: "linkedin",
    direction: "outbound",
    subject: "Connection request — Capital placement services",
    body: "Hi Sarah, I noticed Pinnacle Hospitality's exciting Ft. Lauderdale project. We specialize in hospitality capital placement...",
    template_id: null,
    status: "delivered",
    scheduled_at: null,
    sent_at: "2026-03-04T11:00:00Z",
    sequence_position: 1,
    sequence_id: null,
    compliance_approved: true,
    compliance_approved_by: "system",
    compliance_approved_at: "2026-03-04T10:55:00Z",
    created_by: null,
    created_at: "2026-03-04T10:50:00Z",
  },
  {
    id: "out-5",
    contact_id: "con-1",
    project_id: "proj-1",
    channel: "email",
    direction: "inbound",
    subject: "Re: Vertex Ashburn Phase 2 — Capital Partner Opportunity",
    body: "Thanks for reaching out. We're definitely interested in discussing this further. Can we schedule a call next week?",
    template_id: null,
    status: "replied",
    scheduled_at: null,
    sent_at: "2026-03-06T09:30:00Z",
    sequence_position: null,
    sequence_id: null,
    compliance_approved: false,
    compliance_approved_by: null,
    compliance_approved_at: null,
    created_by: null,
    created_at: "2026-03-06T09:30:00Z",
  },
];

export const MOCK_COMPLIANCE_LOG: ComplianceLogEntry[] = [
  {
    id: "comp-1",
    actor_id: null,
    action: "outreach_sent",
    entity_type: "outreach",
    entity_id: "out-1",
    details: { channel: "email", contact: "Michael Chen", project: "Vertex Ashburn Phase 2", subject: "Capital Partner Opportunity" },
    disclosure_text: "This communication is sent on behalf of [Firm Name], a registered broker-dealer. All securities activities are conducted through and supervised by the firm.",
    firm_approval_required: false,
    firm_approved: null,
    firm_approved_by: null,
    firm_approved_at: null,
    created_at: "2026-03-05T16:00:00Z",
  },
  {
    id: "comp-2",
    actor_id: null,
    action: "project_stage_changed",
    entity_type: "project",
    entity_id: "proj-1",
    details: { from: "qualifying", to: "engaged", project: "Vertex Ashburn Phase 2" },
    disclosure_text: null,
    firm_approval_required: false,
    firm_approved: null,
    firm_approved_by: null,
    firm_approved_at: null,
    created_at: "2026-03-01T14:30:00Z",
  },
  {
    id: "comp-3",
    actor_id: null,
    action: "outreach_sent",
    entity_type: "outreach",
    entity_id: "out-2",
    details: { channel: "email", contact: "James Wilson", project: "The Vue at Knox", subject: "Preferred Equity Discussion" },
    disclosure_text: "This communication is sent on behalf of [Firm Name], a registered broker-dealer.",
    firm_approval_required: false,
    firm_approved: null,
    firm_approved_by: null,
    firm_approved_at: null,
    created_at: "2026-03-06T10:00:00Z",
  },
  {
    id: "comp-4",
    actor_id: null,
    action: "project_submitted",
    entity_type: "project",
    entity_id: "proj-5",
    details: { project: "SunGrid Solar Farm", capital_partners: 2, submission_type: "debt + equity" },
    disclosure_text: "Project submitted to capital partners under firm supervision. Fee arrangement: 4.0% placement fee.",
    firm_approval_required: true,
    firm_approved: true,
    firm_approved_by: "partner",
    firm_approved_at: "2026-03-06T12:00:00Z",
    created_at: "2026-03-06T10:30:00Z",
  },
  {
    id: "comp-5",
    actor_id: null,
    action: "fee_agreement_drafted",
    entity_type: "project",
    entity_id: "proj-2",
    details: { project: "The Vue at Knox", fee_pct: 6.0, estimated_fee: 1800000 },
    disclosure_text: "Fee agreement for equity placement. 6% of placed capital. Subject to firm approval.",
    firm_approval_required: true,
    firm_approved: false,
    firm_approved_by: null,
    firm_approved_at: null,
    created_at: "2026-03-07T09:00:00Z",
  },
  {
    id: "comp-6",
    actor_id: null,
    action: "outreach_sent",
    entity_type: "outreach",
    entity_id: "out-4",
    details: { channel: "linkedin", contact: "Sarah Martinez", project: "Pinnacle Courtyard" },
    disclosure_text: "LinkedIn outreach for capital placement. Conducted under firm supervision.",
    firm_approval_required: false,
    firm_approved: null,
    firm_approved_by: null,
    firm_approved_at: null,
    created_at: "2026-03-04T11:00:00Z",
  },
];

export const MOCK_OPPORTUNITIES: Opportunity[] = [
  {
    id: "opp-1",
    project_id: "proj-1",
    capital_source_org_id: null,
    capital_source_contact_id: null,
    opportunity_type: "debt_placement",
    status: "in_discussion",
    amount: 40000000,
    fee_pct: 5.0,
    fee_amount: 2000000,
    notes: "Senior debt tranche for remaining $40M. Discussing with two institutional lenders.",
    lost_reason: null,
    created_by: null,
    created_at: "2026-03-03T10:00:00Z",
    updated_at: "2026-03-07T14:00:00Z",
  },
  {
    id: "opp-2",
    project_id: "proj-1",
    capital_source_org_id: null,
    capital_source_contact_id: null,
    opportunity_type: "equity_placement",
    status: "approached",
    amount: 40000000,
    fee_pct: 6.0,
    fee_amount: 2400000,
    notes: "Preferred equity for the remaining $40M. Approaching family offices.",
    lost_reason: null,
    created_by: null,
    created_at: "2026-03-04T09:00:00Z",
    updated_at: "2026-03-06T16:00:00Z",
  },
  {
    id: "opp-3",
    project_id: "proj-2",
    capital_source_org_id: null,
    capital_source_contact_id: null,
    opportunity_type: "equity_placement",
    status: "term_sheet",
    amount: 30000000,
    fee_pct: 6.0,
    fee_amount: 1800000,
    notes: "Preferred equity at 12% return. Term sheet issued, awaiting sponsor review.",
    lost_reason: null,
    created_by: null,
    created_at: "2026-02-28T11:00:00Z",
    updated_at: "2026-03-08T08:00:00Z",
  },
  {
    id: "opp-4",
    project_id: "proj-5",
    capital_source_org_id: null,
    capital_source_contact_id: null,
    opportunity_type: "debt_placement",
    status: "committed",
    amount: 40000000,
    fee_pct: 4.0,
    fee_amount: 1600000,
    notes: "Tax equity bridge loan committed by infrastructure fund.",
    lost_reason: null,
    created_by: null,
    created_at: "2026-03-01T14:00:00Z",
    updated_at: "2026-03-07T10:00:00Z",
  },
  {
    id: "opp-5",
    project_id: "proj-3",
    capital_source_org_id: null,
    capital_source_contact_id: null,
    opportunity_type: "debt_placement",
    status: "identified",
    amount: 35000000,
    fee_pct: 5.5,
    fee_amount: 1925000,
    notes: "Construction loan needed. Identified 3 potential lenders in the hospitality space.",
    lost_reason: null,
    created_by: null,
    created_at: "2026-03-06T08:00:00Z",
    updated_at: "2026-03-06T08:00:00Z",
  },
  {
    id: "opp-6",
    project_id: "proj-5",
    capital_source_org_id: null,
    capital_source_contact_id: null,
    opportunity_type: "equity_placement",
    status: "lost",
    amount: 20000000,
    fee_pct: 4.5,
    fee_amount: 900000,
    notes: null,
    lost_reason: "Capital partner required 15% IRR, sponsor only willing to offer 12%",
    created_by: null,
    created_at: "2026-02-20T10:00:00Z",
    updated_at: "2026-03-02T16:00:00Z",
  },
];

export const MOCK_NEWSLETTERS: Newsletter[] = [
  {
    id: "nl-1",
    title: "Q1 2026 Data Center Capital Markets Update",
    subject_line: "Data Center Deal Flow: $1.2B in New Opportunities",
    body_html: null,
    body_text: "The data center sector continues to see unprecedented demand driven by AI infrastructure buildout. Northern Virginia remains the top market with 450+ MW in active development. Key trends this quarter include...",
    sector_focus: ["data_center"],
    status: "sent",
    ai_draft: {},
    editor_notes: "Solid open rate. Consider adding deal case studies next time.",
    recipient_count: 142,
    sent_at: "2026-02-15T09:00:00Z",
    scheduled_at: null,
    approved_by: "partner",
    created_by: null,
    created_at: "2026-02-10T14:00:00Z",
    updated_at: "2026-02-15T09:00:00Z",
  },
  {
    id: "nl-2",
    title: "March 2026 CRE & Hospitality Deal Spotlight",
    subject_line: "New Multifamily & Hotel Opportunities in the Sunbelt",
    body_html: null,
    body_text: "This month we're highlighting two exciting opportunities in the CRE and hospitality sectors. The Vue at Knox in Dallas represents a $95M luxury multifamily opportunity with senior debt already secured...",
    sector_focus: ["cre", "hospitality"],
    status: "draft",
    ai_draft: { generated_at: "2026-03-06T10:00:00Z", model: "claude-3.5-sonnet" },
    editor_notes: null,
    recipient_count: 0,
    sent_at: null,
    scheduled_at: null,
    approved_by: null,
    created_by: null,
    created_at: "2026-03-06T10:00:00Z",
    updated_at: "2026-03-07T15:00:00Z",
  },
  {
    id: "nl-3",
    title: "Energy & Infrastructure Monthly",
    subject_line: "Solar + Storage: $660M in Active Deal Pipeline",
    body_html: null,
    body_text: "The renewable energy sector is experiencing a surge in capital deployment, particularly in solar + battery storage projects. We're tracking over $660M in active energy infrastructure deals...",
    sector_focus: ["energy", "infrastructure"],
    status: "review",
    ai_draft: { generated_at: "2026-03-07T08:00:00Z", model: "claude-3.5-sonnet" },
    editor_notes: "Needs compliance review before sending. Check disclosure language.",
    recipient_count: 0,
    sent_at: null,
    scheduled_at: "2026-03-10T09:00:00Z",
    approved_by: null,
    created_by: null,
    created_at: "2026-03-07T08:00:00Z",
    updated_at: "2026-03-08T06:00:00Z",
  },
];

// Helper functions
export function getMockSourceRecord(id: string): SourceRecord | undefined {
  return MOCK_SOURCE_RECORDS.find((s) => s.id === id);
}

export function getMockOutreachForContact(contactId: string): Outreach[] {
  return MOCK_OUTREACH.filter((o) => o.contact_id === contactId);
}

export function getMockOutreachForProject(projectId: string): Outreach[] {
  return MOCK_OUTREACH.filter((o) => o.project_id === projectId);
}

export function getMockOpportunitiesForProject(projectId: string): Opportunity[] {
  return MOCK_OPPORTUNITIES.filter((o) => o.project_id === projectId);
}
