import type {
  Organization, Contact, Project, SourceRecord, Opportunity,
  Outreach, ComplianceLogEntry, ActivityLogEntry,
} from "@/lib/types";

// ============================================================
// Mock Data — Used when Supabase is not configured
// ============================================================

export const MOCK_ORGANIZATIONS: Organization[] = [
  {
    id: "org-1",
    name: "Vertex Data Systems",
    type: "developer",
    sector: "data_center",
    website: "https://vertexdata.com",
    hq_city: "Ashburn",
    hq_state: "VA",
    employee_count: 450,
    annual_revenue_range: "$100M-$500M",
    description: "Hyperscale data center developer focused on Northern Virginia and Dallas markets. Currently developing 3 campuses totaling 240MW.",
    linkedin_url: "https://linkedin.com/company/vertex-data",
    tags: ["hyperscale", "tier-1-developer"],
    metadata: {},
    source: "news",
    created_by: null,
    archived_at: null,
    created_at: "2026-02-15T10:00:00Z",
    updated_at: "2026-03-01T14:30:00Z",
  },
  {
    id: "org-2",
    name: "Pinnacle Hospitality Group",
    type: "sponsor",
    sector: "hospitality",
    website: "https://pinnaclehg.com",
    hq_city: "Miami",
    hq_state: "FL",
    employee_count: 200,
    annual_revenue_range: "$50M-$100M",
    description: "Full-service hospitality sponsor specializing in select-service and extended-stay hotels across the Southeast.",
    linkedin_url: null,
    tags: ["hospitality", "southeast"],
    metadata: {},
    source: "referral",
    created_by: null,
    archived_at: null,
    created_at: "2026-02-20T08:00:00Z",
    updated_at: "2026-02-28T11:00:00Z",
  },
  {
    id: "org-3",
    name: "Skyline Development Partners",
    type: "developer",
    sector: "cre",
    website: "https://skylinedev.com",
    hq_city: "Dallas",
    hq_state: "TX",
    employee_count: 120,
    annual_revenue_range: "$50M-$100M",
    description: "Multifamily and mixed-use developer with a pipeline of 2,800 units across Texas and the Sunbelt.",
    linkedin_url: "https://linkedin.com/company/skyline-dev",
    tags: ["multifamily", "sunbelt", "ground-up"],
    metadata: {},
    source: "linkedin",
    created_by: null,
    archived_at: null,
    created_at: "2026-01-10T09:00:00Z",
    updated_at: "2026-03-05T16:00:00Z",
  },
  {
    id: "org-4",
    name: "Meridian Energy Capital",
    type: "investor",
    sector: "energy",
    website: "https://meridiancap.com",
    hq_city: "Houston",
    hq_state: "TX",
    employee_count: 35,
    annual_revenue_range: "$10M-$50M",
    description: "Energy infrastructure investor deploying capital into solar, battery storage, and transmission projects.",
    linkedin_url: null,
    tags: ["solar", "battery-storage", "investor"],
    metadata: {},
    source: "manual",
    created_by: null,
    archived_at: null,
    created_at: "2026-03-01T12:00:00Z",
    updated_at: "2026-03-06T09:00:00Z",
  },
  {
    id: "org-5",
    name: "CoreBridge Industrial",
    type: "developer",
    sector: "cre",
    website: "https://corebridgeindustrial.com",
    hq_city: "Phoenix",
    hq_state: "AZ",
    employee_count: 80,
    annual_revenue_range: "$50M-$100M",
    description: "Industrial and logistics developer building spec warehouses and last-mile distribution facilities.",
    linkedin_url: "https://linkedin.com/company/corebridge",
    tags: ["industrial", "logistics", "spec"],
    metadata: {},
    source: "news",
    created_by: null,
    archived_at: null,
    created_at: "2026-02-25T14:00:00Z",
    updated_at: "2026-03-04T10:00:00Z",
  },
];

export const MOCK_CONTACTS: Contact[] = [
  {
    id: "con-1",
    organization_id: "org-1",
    first_name: "Michael",
    last_name: "Chen",
    title: "Managing Director, Development",
    email: "mchen@vertexdata.com",
    phone: "703-555-0142",
    linkedin_url: "https://linkedin.com/in/michaelchen",
    is_decision_maker: true,
    relationship_status: "warm",
    notes: "Met at NAIOP conference. Interested in talking about equity for Phase 2 campus.",
    tags: ["decision-maker", "data-center"],
    source: "conference",
    created_by: null,
    archived_at: null,
    created_at: "2026-02-15T10:30:00Z",
    updated_at: "2026-03-02T09:00:00Z",
  },
  {
    id: "con-2",
    organization_id: "org-2",
    first_name: "Sarah",
    last_name: "Martinez",
    title: "VP of Acquisitions",
    email: "smartinez@pinnaclehg.com",
    phone: "305-555-0198",
    linkedin_url: null,
    is_decision_maker: true,
    relationship_status: "cold",
    notes: null,
    tags: ["hospitality", "acquisitions"],
    source: "linkedin",
    created_by: null,
    archived_at: null,
    created_at: "2026-02-20T08:30:00Z",
    updated_at: "2026-02-20T08:30:00Z",
  },
  {
    id: "con-3",
    organization_id: "org-3",
    first_name: "James",
    last_name: "Wilson",
    title: "Partner & Head of Development",
    email: "jwilson@skylinedev.com",
    phone: "214-555-0167",
    linkedin_url: "https://linkedin.com/in/jameswilson-skyline",
    is_decision_maker: true,
    relationship_status: "hot",
    notes: "Actively seeking $45M in pref equity for The Vue at Knox. Timeline: Q3 2026 close.",
    tags: ["decision-maker", "active-deal"],
    source: "referral",
    created_by: null,
    archived_at: null,
    created_at: "2026-01-10T09:30:00Z",
    updated_at: "2026-03-07T08:00:00Z",
  },
  {
    id: "con-4",
    organization_id: "org-3",
    first_name: "Emily",
    last_name: "Park",
    title: "Director of Capital Markets",
    email: "epark@skylinedev.com",
    phone: "214-555-0201",
    linkedin_url: null,
    is_decision_maker: false,
    relationship_status: "warm",
    notes: "Day-to-day contact for capital stack discussions.",
    tags: ["capital-markets"],
    source: "referral",
    created_by: null,
    archived_at: null,
    created_at: "2026-01-15T11:00:00Z",
    updated_at: "2026-03-05T14:00:00Z",
  },
  {
    id: "con-5",
    organization_id: "org-5",
    first_name: "Robert",
    last_name: "Nguyen",
    title: "CEO",
    email: "rnguyen@corebridgeindustrial.com",
    phone: "602-555-0134",
    linkedin_url: "https://linkedin.com/in/robertnguyen-corebridge",
    is_decision_maker: true,
    relationship_status: "cold",
    notes: null,
    tags: ["ceo", "industrial"],
    source: "news",
    created_by: null,
    archived_at: null,
    created_at: "2026-02-25T14:30:00Z",
    updated_at: "2026-02-25T14:30:00Z",
  },
];

export const MOCK_PROJECTS: Project[] = [
  {
    id: "proj-1",
    name: "Vertex Ashburn Campus Phase 2",
    organization_id: "org-1",
    sector: "data_center",
    project_type: "ground_up",
    description: "80MW hyperscale data center campus expansion in Ashburn, VA. Phase 2 includes two buildings with 40MW each. Utility power secured through Dominion Energy.",
    location_city: "Ashburn",
    location_state: "VA",
    location_address: null,
    total_project_cost: 180000000,
    debt_sought: 120000000,
    equity_sought: 60000000,
    debt_secured: 80000000,
    equity_secured: 20000000,
    funding_gap: 80000000,
    capital_type: "both",
    stage: "engaged",
    priority_score: 94,
    score_breakdown: {
      sector_fit: 25, deal_size_fit: 20, capital_gap_clarity: 15,
      geographic_desirability: 15, contact_quality: 12, timing_urgency: 7, total: 94,
    },
    target_close_date: "2026-06-30",
    construction_start: "2026-09-01",
    estimated_fee_pct: 5.0,
    estimated_fee_amount: 4000000,
    kevin_share_pct: 50,
    kevin_estimated_fee: 2000000,
    source_type: "news",
    source_url: "https://datacenterdynamics.com/vertex-ashburn-phase2",
    source_record_id: null,
    notes: "Strong sponsor. Power secured. Seeking remaining $80M split between senior debt and pref equity.",
    tags: ["hyperscale", "northern-virginia", "high-priority"],
    metadata: { mw_capacity: 80, utility_provider: "Dominion Energy", fiber_access: true },
    created_by: null,
    archived_at: null,
    created_at: "2026-02-16T10:00:00Z",
    updated_at: "2026-03-06T15:00:00Z",
  },
  {
    id: "proj-2",
    name: "The Vue at Knox — Luxury Multifamily",
    organization_id: "org-3",
    sector: "cre",
    project_type: "ground_up",
    description: "320-unit luxury multifamily development in Knox-Henderson, Dallas. Amenity-rich with rooftop pool, co-working, and ground-floor retail.",
    location_city: "Dallas",
    location_state: "TX",
    location_address: "3400 Knox Street",
    total_project_cost: 95000000,
    debt_sought: 65000000,
    equity_sought: 30000000,
    debt_secured: 65000000,
    equity_secured: 0,
    funding_gap: 30000000,
    capital_type: "equity",
    stage: "qualifying",
    priority_score: 82,
    score_breakdown: {
      sector_fit: 21, deal_size_fit: 18, capital_gap_clarity: 13,
      geographic_desirability: 12, contact_quality: 13, timing_urgency: 5, total: 82,
    },
    target_close_date: "2026-09-15",
    construction_start: "2026-11-01",
    estimated_fee_pct: 6.0,
    estimated_fee_amount: 1800000,
    kevin_share_pct: 50,
    kevin_estimated_fee: 900000,
    source_type: "referral",
    source_url: null,
    source_record_id: null,
    notes: "Senior debt locked with Wells Fargo. Seeking $30M preferred equity. James Wilson is the primary contact.",
    tags: ["multifamily", "luxury", "dallas"],
    metadata: { units: 320, stories: 8 },
    created_by: null,
    archived_at: null,
    created_at: "2026-01-12T14:00:00Z",
    updated_at: "2026-03-07T08:00:00Z",
  },
  {
    id: "proj-3",
    name: "Pinnacle Courtyard — Ft. Lauderdale",
    organization_id: "org-2",
    sector: "hospitality",
    project_type: "ground_up",
    description: "180-key Courtyard by Marriott in Fort Lauderdale beach area. Flagged hotel with strong projected RevPAR.",
    location_city: "Fort Lauderdale",
    location_state: "FL",
    location_address: null,
    total_project_cost: 52000000,
    debt_sought: 35000000,
    equity_sought: 17000000,
    debt_secured: 0,
    equity_secured: 5000000,
    funding_gap: 47000000,
    capital_type: "both",
    stage: "discovered",
    priority_score: 71,
    score_breakdown: {
      sector_fit: 19, deal_size_fit: 16, capital_gap_clarity: 10,
      geographic_desirability: 11, contact_quality: 8, timing_urgency: 7, total: 71,
    },
    target_close_date: null,
    construction_start: null,
    estimated_fee_pct: 5.5,
    estimated_fee_amount: 2585000,
    kevin_share_pct: 50,
    kevin_estimated_fee: 1292500,
    source_type: "linkedin",
    source_url: null,
    source_record_id: null,
    notes: "Early stage. Need to verify sponsor track record and flag status.",
    tags: ["hospitality", "marriott", "florida"],
    metadata: { keys: 180, flag: "Courtyard by Marriott" },
    created_by: null,
    archived_at: null,
    created_at: "2026-02-22T09:00:00Z",
    updated_at: "2026-02-28T11:00:00Z",
  },
  {
    id: "proj-4",
    name: "CoreBridge Logistics Hub — Goodyear",
    organization_id: "org-5",
    sector: "cre",
    project_type: "ground_up",
    description: "850,000 SF spec industrial/logistics facility in Goodyear, AZ. Cross-dock design, 40ft clear height, targeting e-commerce tenants.",
    location_city: "Goodyear",
    location_state: "AZ",
    location_address: null,
    total_project_cost: 78000000,
    debt_sought: 55000000,
    equity_sought: 23000000,
    debt_secured: 0,
    equity_secured: 0,
    funding_gap: 78000000,
    capital_type: "both",
    stage: "discovered",
    priority_score: 65,
    score_breakdown: {
      sector_fit: 21, deal_size_fit: 17, capital_gap_clarity: 5,
      geographic_desirability: 10, contact_quality: 5, timing_urgency: 7, total: 65,
    },
    target_close_date: null,
    construction_start: null,
    estimated_fee_pct: 5.0,
    estimated_fee_amount: 3900000,
    kevin_share_pct: 50,
    kevin_estimated_fee: 1950000,
    source_type: "news",
    source_url: null,
    source_record_id: null,
    notes: "Spec project — no pre-leasing yet. Need to connect with sponsor.",
    tags: ["industrial", "logistics", "spec"],
    metadata: { sqft: 850000, clear_height: 40 },
    created_by: null,
    archived_at: null,
    created_at: "2026-02-26T15:00:00Z",
    updated_at: "2026-03-04T10:00:00Z",
  },
  {
    id: "proj-5",
    name: "SunGrid Solar Farm — West Texas",
    organization_id: "org-4",
    sector: "energy",
    project_type: "ground_up",
    description: "200MW utility-scale solar farm with 50MW/200MWh battery storage. 20-year PPA with major utility secured.",
    location_city: "Pecos",
    location_state: "TX",
    location_address: null,
    total_project_cost: 240000000,
    debt_sought: 180000000,
    equity_sought: 60000000,
    debt_secured: 140000000,
    equity_secured: 40000000,
    funding_gap: 60000000,
    capital_type: "both",
    stage: "submitted",
    priority_score: 78,
    score_breakdown: {
      sector_fit: 18, deal_size_fit: 20, capital_gap_clarity: 14,
      geographic_desirability: 10, contact_quality: 10, timing_urgency: 6, total: 78,
    },
    target_close_date: "2026-08-01",
    construction_start: "2026-10-01",
    estimated_fee_pct: 4.0,
    estimated_fee_amount: 2400000,
    kevin_share_pct: 50,
    kevin_estimated_fee: 1200000,
    source_type: "manual",
    source_url: null,
    source_record_id: null,
    notes: "PPA in place. Strong fundamentals. Submitted to two capital partners.",
    tags: ["solar", "battery-storage", "ppa"],
    metadata: { mw_capacity: 200, battery_mwh: 200, ppa_years: 20 },
    created_by: null,
    archived_at: null,
    created_at: "2026-03-02T10:00:00Z",
    updated_at: "2026-03-06T14:00:00Z",
  },
];

export const MOCK_ACTIVITY: ActivityLogEntry[] = [
  { id: "act-1", user_id: null, action: "created", entity_type: "project", entity_id: "proj-5", details: { name: "SunGrid Solar Farm" }, created_at: "2026-03-06T14:00:00Z" },
  { id: "act-2", user_id: null, action: "stage_changed", entity_type: "project", entity_id: "proj-5", details: { from: "engaged", to: "submitted" }, created_at: "2026-03-06T13:00:00Z" },
  { id: "act-3", user_id: null, action: "outreach_sent", entity_type: "contact", entity_id: "con-1", details: { channel: "email", subject: "Capital partner for data center development" }, created_at: "2026-03-05T16:00:00Z" },
  { id: "act-4", user_id: null, action: "created", entity_type: "organization", entity_id: "org-5", details: { name: "CoreBridge Industrial" }, created_at: "2026-03-04T10:00:00Z" },
  { id: "act-5", user_id: null, action: "score_updated", entity_type: "project", entity_id: "proj-1", details: { old_score: 88, new_score: 94 }, created_at: "2026-03-03T11:00:00Z" },
  { id: "act-6", user_id: null, action: "contact_added", entity_type: "contact", entity_id: "con-4", details: { name: "Emily Park" }, created_at: "2026-03-02T09:00:00Z" },
  { id: "act-7", user_id: null, action: "stage_changed", entity_type: "project", entity_id: "proj-1", details: { from: "qualifying", to: "engaged" }, created_at: "2026-03-01T14:30:00Z" },
];

// Helper to get org by id
export function getMockOrg(id: string): Organization | undefined {
  return MOCK_ORGANIZATIONS.find((o) => o.id === id);
}

export function getMockContact(id: string): Contact | undefined {
  return MOCK_CONTACTS.find((c) => c.id === id);
}

export function getMockProject(id: string): Project | undefined {
  return MOCK_PROJECTS.find((p) => p.id === id);
}

export function getMockContactsForOrg(orgId: string): Contact[] {
  return MOCK_CONTACTS.filter((c) => c.organization_id === orgId);
}

export function getMockProjectsForOrg(orgId: string): Project[] {
  return MOCK_PROJECTS.filter((p) => p.organization_id === orgId);
}
